-- billing-agent · collections upgrade migration
-- Generated by comparing PRODUCTION to STAGING (already validated).
-- ADDITIVE ONLY: no DROP, no data change, existing columns untouched.
-- Run over the DIRECT connection (port 5432). DDL fails on the 6543 pooler.

-- 1a. new enum VALUES on existing types.
--     Deliberately OUTSIDE the transaction: Postgres will not let a value
--     added by ALTER TYPE be used in the same transaction that adds it.
ALTER TYPE "InvoiceStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_PAID';

BEGIN;

-- 1b. new enum types ---------------------------------------------------
DO $$ BEGIN CREATE TYPE "PdcStatus" AS ENUM ('WAREHOUSED', 'DEPOSITED', 'CLEARED', 'BOUNCED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "PtpStatus" AS ENUM ('OPEN', 'KEPT', 'BROKEN');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "ReviewFlag" AS ENUM ('UNCHANGED', 'CHANGED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "Wht2307Status" AS ENUM ('NOT_APPLICABLE', 'PENDING', 'RECEIVED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 2. new columns on existing tables ------------------------------------
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "createdById" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "reviewFlag" "ReviewFlag" DEFAULT 'CHANGED'::"ReviewFlag" NOT NULL;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "amountPaidTotal" DECIMAL(15,2) DEFAULT 0 NOT NULL;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "balanceDue" DECIMAL(15,2);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "wht2307Status" "Wht2307Status" DEFAULT 'NOT_APPLICABLE'::"Wht2307Status" NOT NULL;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "wht2307ReceivedAt" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "followUpPausedUntil" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "suspensionNoticeAt" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "suspendedAt" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "wht2307RequestCount" INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "wht2307RequestedAt" TIMESTAMP(3);

-- 3. indexes -----------------------------------------------------------
CREATE INDEX IF NOT EXISTS "Invoice_followUpPausedUntil_idx" ON public."Invoice" USING btree ("followUpPausedUntil");
CREATE INDEX IF NOT EXISTS "Invoice_wht2307Status_idx" ON public."Invoice" USING btree ("wht2307Status");

COMMIT;

-- 4. NEW TABLES still to create: CollectionRun, InvoicePayment, PdcCheck, PromiseToPay
--    Create these with:  DATABASE_URL="<direct 5432 url>" npx prisma db push
--    (safe: db push only adds what is missing once the above has run)