-- billing-agent · migration 002 — renewal outcome tracking
-- Generated by comparing PRODUCTION to STAGING (already validated).
-- ADDITIVE ONLY: no DROP, no data change, existing columns untouched.
-- Run over the DIRECT connection (port 5432). DDL fails on the 6543 pooler.

BEGIN;

-- 1b. new enum types ---------------------------------------------------
DO $$ BEGIN CREATE TYPE "RenewalOutcome" AS ENUM ('RENEWED', 'NOT_RENEWING', 'LAPSED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

COMMIT;

-- NEXT: create the ContractRenewal table.
--    Create these with:  DATABASE_URL="<direct 5432 url>" npx prisma db push
--    (safe: db push only adds what is missing once the above has run)